// tastaDRAM See — every word on a screen. English only. The words are the
// tasting app's own where it had them; the new ones are the plainest possible.

export const S = {
  appName: "tastaDRAM See",
  sub: "See",
  home: {
    h1: "Your product against three others",
    line: "Four samples, blind. Which do people prefer, and would they buy it at the price?",
    joinTitle: "Join a tasting",
    joinLine: "Enter the code you were given.",
    codePh: "ABC-1234",
    go: "Go",
    organiser: "Running one?",
    organiserLine: "Set up your four samples and get the code to give out.",
    signIn: "Sign in →",
    how: "How it works",
    howLines: [
      "The producer puts four samples on the table, marked A, B, C and D: their own product and three others at a similar price. Nobody tasting knows which is which.",
      "Each person tastes two, says which they prefer, tastes the other two, says which they prefer, then tastes those two winners and picks one.",
      "They are then asked whether they would buy the one they picked, at its price. Then they see the four names.",
      "The producer sees how many people preferred each sample and how many would buy it, for that tasting and for all their tastings together.",
    ],
    foot: "— by tastaDRAM, Edinburgh.",
  },
  guest: {
    loading: "Loading…",
    noSession: "There is no tasting with that code.",
    joinTitle: "Join the tasting",
    yourName: "What shall we call you?",
    yourNamePh: "Your name",
    anonNote: "A name of your own choosing. We keep nothing else about you.",
    nameTaken: "Somebody here is already using that name. Add something to it so people can tell you apart.",
    joinBtn: "Join →",
    waiting: "Waiting for the tasting to start.",
    roundOf: (n: number) => `Comparison ${n} of 3`,
    tastePair: (a: string, b: string) => `Taste ${a} and ${b}.`,
    whichPrefer: "Which do you prefer?",
    finalRound: "Now the two you preferred.",
    buyTitle: "You preferred",
    buyQ: (mat: string, price: string) => `Would you buy ${mat} at ${price}?`,
    yes: "Yes",
    no: "No",
    done: "Done.",
    answersTitle: "The answers",
    yourPick: "Your choice",
    yourBuy: (yes: boolean, price: string) => (yes ? `You would buy it at ${price}.` : `You would not buy it at ${price}.`),
    roomHead: "How everyone chose",
    was: (mat: string, name: string) => `${mat} was ${name}`,
    preferred: (n: number) => (n === 1 ? "preferred by 1" : `preferred by ${n}`),
    wouldBuy: (n: number, of: number) => `${n} of ${of} would buy`,
    detailHead: "Pair by pair",
    notYou: "Not you?",
    joinAsAnother: "Join as a different person",
    somethingWrong: "Something went wrong",
    sample: (mat: string) => `Sample ${mat}`,
  },
  host: {
    sendLinkHead: "Send this link, or show this code",
    copyLink: "Copy link",
    copied: "Copied ✓",
    beforeLine: "Serve away from the table, on plates or in cups marked A, B, C and D. Nobody tasting sees a label.",
    samplesHead: "The four samples",
    yours: "yours",
    startBtn: "Start the tasting",
    revealBtn: "Show the answers to everyone",
    unrevealBtn: "Hide the answers again",
    resultsHead: "The result",
    colSample: "Sample",
    colPreferred: "Preferred by",
    colBuy: "Would buy",
    detailHead: "Pair by pair",
    roomHead: "Who has tasted",
    colWho: "Who",
    colTasted: "Tasted",
    colFinished: "Finished",
    nOfM: (n: number, m: number) => `${n} of ${m}`,
    yes: "Yes",
    nobodyJoined: "Nobody has joined yet.",
    more: "More",
    codeWord: "The code:",
    sessionsList: "All your tastings",
    signOut: "Sign out",
    signInFirst: "Sign in to see this page.",
    signIn: "Sign in →",
    resetDemo: "Reset the demonstration",
    resetDemoDone: "Reset. A clean demonstration is ready.",
    archive: "Archive this tasting",
    archived: "Archived. It no longer counts in your results.",
    unarchive: "Bring it back",
  },
  admin: {
    signInHead: "Producer sign-in",
    signInLede: "Enter your passcode.",
    passcode: "Passcode",
    signIn: "Sign in →",
    noLogin: "No passcode? Set one up",
    registerHead: "Set up a login",
    registerLede: "Two lines. We do not ask for anything else.",
    producer: "Your business",
    producerPh: "Slow Sauce",
    person: "Your name",
    personPh: "Anna",
    registerBtn: "Set up →",
    backToSignIn: "← I have a passcode",
    passcodeHead: "Your passcode",
    passcodeLede: "Write this down. You sign in with it. You can change it further down this page.",
    failed: "That did not work.",
    signedInAs: (name: string) => name,
    createHead: "New tasting",
    sessionName: "Name",
    sessionNamePh: "Saturday, Banchory market",
    location: "Where",
    locationPh: "Banchory",
    currency: "Currency",
    samplesHead: "The four samples",
    samplesLede: "Your product and three others at a similar price. They go on A, B, C and D in this order; only you see which is which.",
    sampleN: (n: number) => `Sample ${n}`,
    name: "Product",
    namePh: "Oat shoyu",
    producerOf: "Producer",
    producerOfPh: "Slow Sauce",
    category: "What it is",
    categoryPh: "shoyu",
    price: "Price",
    size: "Size",
    sizePh: "250 ml",
    mine: "This is my product",
    createBtn: "Create →",
    errName: "Enter a name for the tasting.",
    errMine: "Mark which sample is yours.",
    sessionsHead: "Your tastings",
    noSessions: "No tastings yet.",
    colWhen: "When",
    colTasting: "Tasting",
    colPeople: "People",
    colCode: "Code",
    open: "Open",
    resultsHead: "Your products, all tastings together",
    resultsLede: "Every sample you have put on a table, with how it did.",
    colProduct: "Product",
    colTastings: "Tastings",
    colTasters: "Tasters",
    noResults: "No results yet.",
    changeHead: "Change your passcode",
    changeLede: "Set your own passcode. It replaces the one you signed in with.",
    newPasscode: "New passcode",
    repeatIt: "Repeat it",
    changeBtn: "Change passcode →",
    noMatch: "The two entries do not match.",
    passcodeChanged: "Passcode changed. Use it next time you sign in.",
    signOut: "Sign out",
    demoHead: "Demonstration",
    demoLine: "A tasting that is always ready, with four samples on the table.",
    demoOpen: "Open the demonstration",
  },
};

export const CURRENCIES = ["£", "€", "$", "Kč", "₽", "zł"] as const;
